version: '3.0'
services:
  nginx:
    build: .
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./config/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: php:7.1-fpm
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - .env
volumes:
  db-data: